version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_SERVER_URL=http://backend:3001
    depends_on:
      - backend
    networks:
      - quizlive-network

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
    networks:
      - quizlive-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - quizlive-network

networks:
  quizlive-network:
    driver: bridge
